import antfu from '@antfu/eslint-config'

export default antfu(
    {
        typescript: true,
        vue: true,
        stylistic: false,
    },
    {
        ignores: ['resources/js/tests/**', '**/specs/*', '**/*.spec.js', '**/*.spec.ts'],
    },
    {
        files: ['resources/js/**/*.{js,ts,vue,json}'],
        rules: {
            'vue/html-indent': 'off',
            'vue/attributes-order': 'off',
            'vue/max-attributes-per-line': 'off',
            'vue/mustache-interpolation-spacing': 'off',
            'vue/singleline-html-element-content-newline': 'off',
            'vue/multiline-html-element-content-newline': 'off',
            'vue/v-on-event-hyphenation': 'off',
            'vue/this-in-template': 'off',
            'vue/first-attribute-linebreak': 'off',
            'vue/html-self-closing': 'off',
            'vue/html-quotes': 'off',
            'vue/html-closing-bracket-spacing': 'off',
            'vue/html-closing-bracket-newline': 'off',
            'vue/space-infix-ops': 'off',
            'vue/no-unused-refs': 'off',
            'vue/require-explicit-emits': 'off',
            'vue/v-slot-style': 'off',
            'vue/no-useless-v-bind': 'off',
            'vue/eqeqeq': 'off',
            'vue/component-name-in-template-casing': 'off',
            'vue/component-definition-name-casing': 'off',
            'vue/prop-name-casing': 'off',
            'vue/no-template-shadow': 'off',
            'vue/attribute-hyphenation': 'off',
            'vue/block-order': 'off',
            'vue/define-macros-order': 'off',
            'vue/v-bind-style': 'off',
            'vue/prefer-template': 'off',
            'vue/order-in-components': 'off',
            'vue/component-options-name-casing': 'off',
            'vue/no-multi-spaces': 'off',
            'vue/custom-event-name-casing': 'off',
            'jsonc/no-useless-escape': 'off',
            'array-callback-return': 'off',
            'eqeqeq': 'off',
            'no-unneeded-ternary': 'off',
            'no-sequences': 'off',
            'no-undef': 'off',
            'prefer-const': 'off',
            'prefer-template': 'off',
            'prefer-spread': 'off',
            'object-shorthand': 'off',
            'no-useless-return': 'off',
            'dot-notation': 'off',
            'prefer-regex-literals': 'off',
            'vars-on-top': 'off',
            'no-var': 'off',
            'no-use-before-define': 'off',
            'prefer-arrow-callback': 'off',
            'new-cap': 'off',
            'one-var': 'off',
            'no-self-compare': 'off',
        }
    },
)
