import antfu from '@antfu/eslint-config'

export default antfu(
    {
        typescript: true,
        vue: true,
        stylistic: false,
    },
    {
        ignores: ['resources/js/tests/**', '**/specs/*', '**/*.spec.js', '**/*.spec.ts'],
    },
    {
        files: ['resources/js/**/*.{js,ts,vue,json}'],
        rules: {
            'vue/no-undef-components': ['error', {
                ignorePatterns: [
                    // components/
                    'badge',             'breadcrumbs',
                    'card',              'collapsible',
                    'data-table',        'dictionary-row',
                    'download-link',     'dropdown-item',
                    'dropdown-menu',     'help-button',
                    'image-cropper',     'impersonate-control',
                    'issue-report-form', 'login-form',
                    'markdown-block',    'modal-dialog',
                    'note',              'notification-item',
                    'notification-list', 'object-dictionary',
                    'pagination-links',  'pop-over',
                    'pubmed-citation',   'question-block',
                    'screen-template',   'simple-table',
                    'tab-item',          'tabs-container',
                    'truncate-expander', 'user-menu',
                    // components/forms/
                    'address-input',
                    'button-row',
                    'checkbox',
                    'credentials-input',
                    'data-form-field',
                    'data-form',
                    'date-input',
                    'disease-search-select',
                    'expertises-input',
                    'form-container',
                    'gene-search-select',
                    'input-errors',
                    'input-row',
                    'institution-search-select',
                    'person-search-select',
                    'radio-button-group',
                    'radio-button',
                    'search-select',
                    'step-input',
                    'timezone-search-select',
                    'user-defined-mail-form',
                    'website-attestation',
                    // components/butons/
                    'checkmark-icon-button',
                    'edit-icon-button',
                    'refresh-button',
                    'remove-button',
                    'trash-icon-button',
                    // components/icons/
                    'icon-add',            'icon-arrow-down',
                    'icon-arrow-right',    'icon-base',
                    'icon-bug',            'icon-checkmark',
                    'icon-cheveron-down',  'icon-cheveron-left',
                    'icon-cheveron-right', 'icon-cheveron-up',
                    'icon-close',          'icon-coi',
                    'icon-download',       'icon-edit',
                    'icon-envelope',       'icon-exclamation',
                    'icon-external-link',  'icon-filter',
                    'icon-info',           'icon-lock',
                    'icon-menu',           'icon-notification',
                    'icon-printer',        'icon-question',
                    'icon-refresh',        'icon-reply',
                    'icon-review',         'icon-search',
                    'icon-trash',          'icon-user',
                    'icon-view-hide',      'icon-view',
                    'zoom-in-icon',        'zoom-out-icon',
                    // components/links/
                    'coi-policy-link',
                    'coordinator-resource-link',
                    'faq-link',
                    'gcep-quick-guide-link',
                    'gcep-recuration-process-link',
                    'gci-link',
                    'gene-tracker-link',
                    'lumping-and-splitting-link',
                    'publication-policy-link',
                    'training-materials-link',
                    'vcep-protocol-link',
                    'website-link',
                    // vue router
                    'router-link',
                    'router-view',
                    // extras
                    'static-alert',
                    'submission-wrapper',
                    'screen-template',
                    'popper',
                    'popover',
                    'group-breadcrumbs',
                ],
            }],
            'jsonc/no-useless-escape': 'off',
            'perfectionist/sort-imports': 'off',
            'perfectionist/sort-named-imports': 'off',
            'perfectionist/sort-named-exports': 'off',
        }
    },
)
