<?php

namespace App\Console\Commands\Dev;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class ExportConsortiumIdentityRolloutSql extends Command
{
    protected $signature = 'consortium-identities:export-rollout-sql
                            {import_batch_uuid}
                            {output_directory}
                            {--force}';

    protected $description = 'Generate GPM and GeneTracker SQL files for Clerk identity rollout';

    public function handle(): int
    {
        $importBatchUuid = $this->argument('import_batch_uuid');
        $outputDirectory = rtrim($this->argument('output_directory'), DIRECTORY_SEPARATOR);

        if (!File::exists($outputDirectory)) {
            File::makeDirectory($outputDirectory, 0755, true);
        }

        $gpmPath = $outputDirectory . DIRECTORY_SEPARATOR . 'gpm-user-identity-updates.sql';
        $gtPath = $outputDirectory . DIRECTORY_SEPARATOR . 'gt-user-identity-updates.sql';

        if (
            !$this->option('force') &&
            (File::exists($gpmPath) || File::exists($gtPath))
        ) {
            $this->error('One or both output files already exist. Use --force to overwrite them.');
            return self::FAILURE;
        }

        $rows = DB::table('consortium_identity_import_rows as r')
            ->join('consortium_identity_candidates as c', function ($join) {
                $join->on('c.import_batch_uuid', '=', 'r.import_batch_uuid')
                    ->on('c.canonical_email', '=', 'r.email_normalized');
            })
            ->where('r.import_batch_uuid', $importBatchUuid)
            ->where('c.clerk_import_status', 'imported')
            ->select([
                'r.source_system',
                'r.local_user_id',
                'r.email_normalized as email',
                'r.gpm_uuid',
                'c.resolved_gpm_uuid as clingen_uuid',
                'c.clerk_user_id',
            ])
            ->orderBy('r.source_system')
            ->orderBy('r.local_user_id')
            ->get();

        if ($rows->isEmpty()) {
            $this->error("No successfully imported identities found for batch {$importBatchUuid}.");
            return self::FAILURE;
        }

        $gpmSql = [];
        $gtSql = [];

        $gpmSql[] = '-- Generated by consortium-identities:export-rollout-sql';
        $gpmSql[] = "-- Import batch: {$importBatchUuid}";
        $gpmSql[] = 'START TRANSACTION;';
        $gpmSql[] = '';

        $gtSql[] = '-- Generated by consortium-identities:export-rollout-sql';
        $gtSql[] = "-- Import batch: {$importBatchUuid}";
        $gtSql[] = 'START TRANSACTION;';
        $gtSql[] = '';

        foreach ($rows as $row) {
            if (!$row->clerk_user_id || !$row->clingen_uuid) {
                continue;
            }

            if ($row->source_system === 'GPM') {
                $gpmSql[] = $this->buildGpmUpdate($row);
            }

            if ($row->source_system === 'GT') {
                $gtSql[] = $this->buildGtUpdate($row);
            }
        }

        $gpmSql[] = '';
        $gpmSql[] = 'COMMIT;';

        $gtSql[] = '';
        $gtSql[] = 'COMMIT;';

        File::put($gpmPath, implode(PHP_EOL, $gpmSql) . PHP_EOL);
        File::put($gtPath, implode(PHP_EOL, $gtSql) . PHP_EOL);

        $this->info("Generated:");
        $this->line("  {$gpmPath}");
        $this->line("  {$gtPath}");

        return self::SUCCESS;
    }

    private function buildGpmUpdate(object $row): string
    {
        $email = $this->quote($row->email);
        $uuid = $this->quote($row->clingen_uuid);
        $clerkUserId = $this->quote($row->clerk_user_id);

        return <<<SQL
UPDATE people
SET clerk_user_id = {$clerkUserId}
WHERE uuid = {$uuid}
  AND LOWER(email) = {$email}
  AND (clerk_user_id IS NULL OR clerk_user_id = {$clerkUserId});
SQL;
    }

    private function buildGtUpdate(object $row): string
    {
        $gtUserId = (int) $row->local_user_id;
        $email = $this->quote($row->email);
        $uuid = $this->quote($row->clingen_uuid);
        $clerkUserId = $this->quote($row->clerk_user_id);

        return <<<SQL
UPDATE users
SET clingen_uuid = {$uuid},
    clerk_user_id = {$clerkUserId}
WHERE id = {$gtUserId}
  AND LOWER(email) = {$email}
  AND (clingen_uuid IS NULL OR clingen_uuid = {$uuid})
  AND (clerk_user_id IS NULL OR clerk_user_id = {$clerkUserId});
SQL;
    }

    private function quote(?string $value): string
    {
        return DB::getPdo()->quote((string) $value);
    }
}