MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysql -u root <<EOF
CREATE DATABASE ${GT_DB_DATABASE};
USE ${GT_DB_DATABASE};
CREATE USER '${GT_DB_USERNAME}'@'%' IDENTIFIED WITH mysql_native_password BY '${GT_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${GT_DB_DATABASE}.* TO '${GT_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
EOF
